name: Test
on: [push]

jobs:

  test:
    name: Test with ${{ matrix.go }} on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.12, 1.13]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
